### ISSUE TITLE
Does not implement VS Code symbol information

### ISSUE THREAD

**Issue by rossvz** [lexical-lsp/vscode-lexical#46]
Hey! 
First off - very impressed with how much this plugin _does_ do already - and it's incredibly fast!

I realize this project is very much still in active development so I understand why some of these features may not be around, but wanted to surface it just in case not everyone uses this workflow.

I often navigate around a large file with "Go To Symbol" in VS code, which lets you start typing part of a function name and just between functions or test definitions in a file! It works better than a standard search since it's all scoped to function definitions, not calls!

It doesn't look like those are provided yet!

![image](https://github.com/lexical-lsp/vscode-lexical/assets/9866589/d359ead8-7460-43f9-8c0b-bd881e7f3f55)

**Comment by scottming** [comment]
Yes, this feature is called document symbols, while the one for the entire project is workspace symbols. These are all in the plan. We are carrying out some foundational work on indexing in the lexical repository.

**Comment by Blond11516** [comment]
Hi @rossvz!

As Scott said, this feature is planned for support eventually, but it will have to wait after indexing (which is being actively worked on) because having a complete index will massively simplify the implementation.

Given this is an LSP feature and should be transparent for clients, I'm going to close this issue. There's already [an issue](https://github.com/lexical-lsp/lexical/issues/382) for this on the Lexical repo, which you can follow for updates.
