### ISSUE TITLE
HEEx heredoc wrapped in function breaks further highlighting

### ISSUE THREAD

**Issue by zolrath** [lexical-lsp/vscode-lexical#77]
Hello!
When using a HEEx heredoc within a function the `""")` section causes further syntax highlighting to break.

```elixir
  test "breaks syntax highlighting" do
    assigns = %{}
    example = "Hello"

    assert example =~ "Hello"

    component =
      rendered_to_string(~H"""
      <.thing type="test" />
      """)

    assert component =~ "This should be green"
  end
  ```
Seems like it works properly on GitHub, here's a screenshot from VS Code!
 ![image](https://github.com/lexical-lsp/vscode-lexical/assets/454563/0269ffa9-2bc8-40a0-b0c8-5a95e40a61e8)

Thanks for the great work on Lexical!

**Comment by Blond11516** [comment]
Hi @zolrath!

Thanks a lot for the report, but I believe this is an issue with the Phoenix Framework extension rather than Lexical. [Their grammar](https://github.com/phoenixframework/vscode-phoenix/blob/main/syntaxes/elixir-heex.json#L14) for the `H` sigil enforces that the heredoc delimiters (sequence of 3 double quotes) appears at the very end of the line (with optional sigil arguments). This is what causes `""")` to not be interpreted as closing the sigil and the rest of the document is thus interperted as being part of the sigil.

Interestingly, this only appears to be the case with heredoc separators. None of the other separators have this requirement.

I'd suggest you open an issue/PR over there.

**Comment by zolrath** [comment]
Oh dang, I thought I had removed all other Elixir/Phoenix extensions before reporting this, sorry about that!
I'll make a report over there, thanks!

**Comment by Blond11516** [comment]
No worries, mistakes happen!

Adding links to the vscode-phoenix issue and corresponding PR for future reference:
- issue: https://github.com/phoenixframework/vscode-phoenix/issues/7
- PR: https://github.com/phoenixframework/vscode-phoenix/pull/25
